# Generated by Django 4.2.5 on 2023-10-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hours_of_operation',
            field=models.TimeField(),
        ),
    ]
