# Generated by Django 4.2.5 on 2023-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hours_of_operation',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hour',
            field=models.TimeField(null=True),
        ),
    ]
