# Generated by Django 4.2.5 on 2023-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurant_hours_of_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='product_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/img'),
        ),
    ]
