<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-31 12:48
=======
# Generated by Django 4.2.5 on 2023-11-06 09:58
>>>>>>> b53cc28ad0a880f204d4f4f3d7978fd229965cb1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
