# Generated by Django 4.2.6 on 2023-12-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='fooddelivery.menu'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='fooddelivery.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fooddelivery.portion'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_adresses', to='fooddelivery.adress'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(through='fooddelivery.OrderItem', to='fooddelivery.menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_adresses', to='fooddelivery.adress'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='fooddelivery.menu_category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='menus', to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='menu',
            name='portions',
            field=models.ManyToManyField(blank=True, related_name='menus', to='fooddelivery.portion'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='extracategory',
            name='extras',
            field=models.ManyToManyField(related_name='extra_categories', to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='extras',
            field=models.ManyToManyField(blank=True, to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='cart',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='fooddelivery.menu'),
        ),
        migrations.AddField(
            model_name='cart',
            name='portion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fooddelivery.portion'),
        ),
        migrations.AddField(
            model_name='adress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adress',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_addresses', to='restaurants.province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='customers', to='fooddelivery.adress'),
        ),
        migrations.AddField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
