# Generated by Django 4.2.5 on 2023-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_category', models.CharField(max_length=150)),
                ('menu_category', models.CharField(max_length=150)),
            ],
        ),
    ]
