# Generated by Django 4.2.5 on 2023-09-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularUser',
        ),
    ]
