# Generated by Django 4.2.5 on 2023-10-30 11:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_category',
            name='menu_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
