# Generated by Django 4.2.5 on 2023-10-10 15:55

from django.db import migrations, models
import fooddelivery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[fooddelivery.validators.phone_number_validator]),
        ),
    ]
