# Generated by Django 4.2.6 on 2023-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_alter_menu_created_at_alter_menu_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=1234567890, max_length=15),
            preserve_default=False,
        ),
    ]
