# Generated by Django 4.2.5 on 2023-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_alter_menu_created_at_alter_menu_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
