# Generated by Django 4.2.6 on 2023-10-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
    ]
