# Generated by Django 4.2.5 on 2023-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(choices=[('İstanbul', 'İstanbul')], default='İstanbul', max_length=100),
        ),
    ]
