# Generated by Django 4.2.6 on 2023-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='extrasas', to='fooddelivery.menu'),
        ),
        migrations.AddField(
            model_name='portion',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='portionses', to='fooddelivery.menu'),
        ),
    ]
