# Generated by Django 4.2.5 on 2023-10-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
