# Generated by Django 4.2.5 on 2023-12-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_alter_adress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(choices=[('İstanbul', 'İstanbul')], default=None, max_length=100),
        ),
    ]
