# Generated by Django 4.2.5 on 2023-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
