# Generated by Django 4.2.6 on 2023-12-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_extras_menu_portion_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='menu',
        ),
        migrations.AddField(
            model_name='extras',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extrasas', to='fooddelivery.menu'),
        ),
        migrations.AddField(
            model_name='portion',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portionsas', to='fooddelivery.menu'),
        ),
    ]
