# Generated by Django 4.2.5 on 2023-10-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_category_restaurant_phone_number_and_more'),
        ('fooddelivery', '0003_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'db_table': 'menu_category',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
