# Generated by Django 4.2.6 on 2023-11-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
