# Generated by Django 4.2.5 on 2023-10-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_menu_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_category',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='menu_category',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='fooddelivery.menu_category'),
        ),
    ]
