# Generated by Django 4.2.5 on 2023-09-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_product_mage_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
