# Generated by Django 4.2.6 on 2023-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_remove_extras_menu_remove_portion_menu_extras_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='menu',
        ),
    ]
