# Generated by Django 4.2.6 on 2023-12-18 14:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_alter_adress_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'extras',
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Portion',
                'verbose_name_plural': 'Portions',
                'db_table': 'portions',
            },
        ),
        migrations.CreateModel(
            name='Extracategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('extras', models.ManyToManyField(related_name='extra_categories', to='fooddelivery.extras')),
            ],
            options={
                'verbose_name': 'Extra Category',
                'verbose_name_plural': 'Extra Categories',
                'db_table': 'extra_category',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='menus', to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='menu',
            name='portions',
            field=models.ManyToManyField(blank=True, related_name='menus', to='fooddelivery.portion'),
        ),
    ]
