# Generated by Django 4.2.5 on 2023-10-23 14:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_product_image_and_more'),
        ('fooddelivery', '0005_remove_menu_category_menu_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/img')),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sets', to='fooddelivery.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sets', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Product Set',
                'verbose_name_plural': 'Product Sets',
                'db_table': 'product_set',
            },
        ),
    ]
