# Generated by Django 4.2.6 on 2023-12-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0005_remove_extras_menu_remove_portion_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='portion',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
