# Generated by Django 4.2.6 on 2023-12-18 14:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0005_extras_portion_extracategory_menu_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
