# Generated by Django 4.2.5 on 2023-10-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_customer_groups_customer_is_superuser_and_more'),
        ('fooddelivery', '0005_remove_menu_category_menu_category_and_more'),
    ]

    operations = [
    ]
