# Generated by Django 4.2.6 on 2023-11-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0004_customer_date_joined'),
        ('fooddelivery', '0006_customer_date_joined'),
    ]

    operations = [
    ]
