# Generated by Django 4.2.5 on 2023-10-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0006_productset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSet',
        ),
    ]
