# Generated by Django 4.2.5 on 2023-09-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0006_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='fooddelivery_product',
        ),
    ]
