# Generated by Django 4.2.6 on 2023-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0007_alter_portion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='portions',
            field=models.ManyToManyField(related_name='menus', to='fooddelivery.portion'),
        ),
    ]
