# Generated by Django 4.2.6 on 2023-11-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0007_merge_20231106_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='fooddelivery.menu'),
        ),
    ]
