# Generated by Django 4.2.6 on 2023-12-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0007_cart_extras_cart_portions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='portions',
        ),
        migrations.AddField(
            model_name='cart',
            name='portion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fooddelivery.portion'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='extras',
            field=models.ManyToManyField(blank=True, to='fooddelivery.extras'),
        ),
    ]
