# Generated by Django 4.2.5 on 2023-10-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0008_remove_cart_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
