# Generated by Django 4.2.6 on 2023-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0008_alter_orderitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='nakit', max_length=100),
        ),
    ]
