# Generated by Django 4.2.6 on 2023-12-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0008_remove_cart_portions_cart_portion_alter_cart_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='fooddelivery.extras'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fooddelivery.portion'),
        ),
    ]
