# Generated by Django 4.2.5 on 2023-12-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0010_order_reviewed_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fooddelivery.order'),
            preserve_default='True',
        ),
    ]
