# Generated by Django 4.2.5 on 2023-09-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0014_order_is_active_order_user_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
