# Generated by Django 4.2.5 on 2023-10-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0015_order_orderitem_order_products_order_user'),
        ('fooddelivery', '0016_order'),
    ]

    operations = [
    ]
