# Generated by Django 4.2.5 on 2023-10-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0017_merge_20231002_1610'),
        ('fooddelivery', '0018_rename_user_order_customer_alter_customer_name'),
    ]

    operations = [
    ]
